### ISSUE TITLE
Bug: No play button for tour

### ISSUE THREAD

**Issue by dnielsen2022** [blackgirlbytes/rock-paper-scissors-copilot#1]
### Describe the bug

When I open the template into the codespace, I don't get the play button. It looks like it believes there is an issue with the tour file:
![Screenshot 2023-03-07 at 10 11 21 AM](https://user-images.githubusercontent.com/99437618/223463953-3295bac9-26e1-48b6-8999-ec779f3335c8.png)
![Screenshot 2023-03-07 at 10 11 45 AM](https://user-images.githubusercontent.com/99437618/223463980-94d0d321-4dc4-48ad-adc9-60f83fa5c930.png)
![Screenshot 2023-03-07 at 10 11 53 AM](https://user-images.githubusercontent.com/99437618/223464011-16a7e517-401d-41a1-b99d-bb2a8492c548.png)
![Screenshot 2023-03-07 at 10 12 01 AM](https://user-images.githubusercontent.com/99437618/223464033-f116aa24-86d5-4fa6-8346-452693e5f515.png)
![Screenshot 2023-03-07 at 10 14 55 AM](https://user-images.githubusercontent.com/99437618/223464516-9d543257-cd7e-4f01-bd1c-407ea35fcaa0.png)

### Steps to reproduce

Screenshots above

### Affected services

opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blackgirlbytes** [comment]
Thank you, @dnielsen2022! I think I might've had an extra new line that made the codetour error out. Also Codespaces does take a bit to load everything. Would you mind trying again and letting me know if you're still experiencing the same issues? Here's a video below where at first it doesn't show me the CodeTour, but after a few minutes the full CodeTour loads.


https://user-images.githubusercontent.com/22990146/223469418-b8a479ef-e602-4a45-bcad-bb73e28b2222.mov

**Comment by dnielsen2022** [comment]
Looks like it is working now!

**Comment by blackgirlbytes** [comment]
Thank you so much for pointing out the error! I appreciate you! @dnielsen2022

**Comment by dnielsen2022** [comment]
No problem. Thanks for building this, it is a fun way to consume and demo these features!
